version: '2.1'

services:
  user:
    build: video-sharing-microservices/User-Microservice
    mem_limit: 250m
    networks:
      - my-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-compose
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    networks:
      - my-network
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  my-network:
    name: my-network
