server:
  application.name: user-microservice
  port: 80

spring.data.mongodb:
  host: localhost
  port: 27017
  database: users-db

app:
  AUTH_SIGNIN_URL: /auth/signin
  AUTH_SIGNUP_URL: /auth/sign-up
  RESPONSE_HEADER: Authorization
  OAUTH2_AUTHORIZATION_COOKIE: oauth2_authorization_cookie
  REDIRECT_COOKIE: redirect_uri
  COMMENT_SERVICE_MAX_TIMEOUT: 2
  VIDEO_SERVICE_MAX_TIMEOUT: 3
  COMMENT_SERVICE_URL: http://comments-service/api/v1
  VIDEO_SERVICE_URL: http://videos-service/api/v1

jwt:
  JWT_SECRET:  c4GS/lhQPY+0k8S9WsDxRUI7ld2tK/BpeFJGRuoGvck4uQqAEa2Dd6LaFaPqnzzTAbB4F/XUbeagL7vGCPkXr8I2S+37HaBRD5+Oagil4artuSbjo/M9D1C3Uec7zxZneare1dcy/pL6qAJUbqn+n1rsWJ3
  TOKEN_HEADER: Authorization
  TOKEN_PREFIX: Bearer
  TOKEN_TYPE: JWT
  EXPIRATION_TIME: 64000000
  TOKEN_ISSUER: user-microservice
  TOKEN_AUDIENCE: users

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 1605797062885242
            clientSecret: 4d4b01b2abe33281e4204153f96154db
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v8.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v8.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v8.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

api:
  common:
    version: 1.0.0
    title: User Microservice
    description: User Microservice description
    termsOfServiceUrl: Terms of service url
    license: License
    licenseUrl: License url

    contact:
      name: Dejan Vuk
      url: my-website.com
      email: my-email@yahoo.com
  controllers: aaa

resilience4j.circuitbreaker:
  backends:
    user:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      failureRateThreshold: 100
      waitDurationInOpenState: 10000
      ringBufferSizeInHalfOpenState: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

resilience4j.retry:
  backends:
    user:
      maxRetryAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError


---
spring.profiles: docker-compose

spring.data.mongodb.host: mongodb_users

---
spring.profiles: prod

spring.data.mongodb.host: mongo-user
