apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
spec:
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
      - name: comment
        image: acrekstest.azurecr.io/azure-comment-microservice:1df0c9c
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "350Mi"
