apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
spec:
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: video-container
        image: acrekstest.azurecr.io/azure-video-microservice:bf1222b
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "350Mi"
