apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gateway
spec:
  tls:
    - hosts:
      - minikube.me
      secretName: tls-certificate
  rules:
  - http:
      paths:
      - path: /api/v1/comment/v1
        backend:
          serviceName: comment
          servicePort: 80
      - path: /api/v1/video
        backend:
          serviceName: video
          servicePort: 80        
      - path: /user
        backend:
          serviceName: user
          servicePort: 80

