kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongo-user
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-user
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mongo-user-sc
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user
spec:
  selector:
    matchLabels:
      app: mongo-user-db
  template:
    metadata:
      labels:
        app: mongo-user-db
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-user
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user
spec:
  selector: mongo-user-db
    app: mongo-comment-db
  ports:
    - port: 27017
      targetPort: 27017
