server:
  application.name: comment-microservice
  port: 80
  servlet:
    context-path: /api/v1

spring.data.mongodb:
  host: localhost
  port: 27017
  database: comment-db

---
spring.profiles: docker-compose

spring.data.mongodb.host: mongodb_comments
