server:
  application.name: comment-microservice
  port: 80
  servlet:
    context-path: /api/v1

spring.data.mongodb:
  host: localhost
  port: 27017
  database: comment-db

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.profiles: docker-compose

spring.data.mongodb.host: mongodb_comments

spring.rabbitmq.host: rabbitmq
